name: flutter_pytorch_lite
description: "PyTorch Lite plugin for Flutter. End-to-end workflow from Training to Deployment for iOS and Android mobile devices."
version: 0.1.0+2
homepage: https://github.com/winfordguo/flutter_pytorch_lite
repository: https://github.com/winfordguo/flutter_pytorch_lite

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.github.winfordguo.flutter_pytorch_lite
        pluginClass: FlutterPytorchLitePlugin
      ios:
        pluginClass: FlutterPytorchLitePlugin

  topics:
    - torch
    - pytorch
    - pytorch-lite
    - pytorch-mobile
    - yolo
    - ai
